### ISSUE TITLE
Source code updates for 1.0.2 branch

### ISSUE THREAD

**Issue by Tarnum-tst** [kzalewski/openssl-1.1.1#2]
Sorry for asking about 1.0.2 branch but maybe You happen to have latest source code patches (1.0.2zj, 1.0.2zk and 1.0.2zl) for it?

Base version (1.0.2zi): https://s3.amazonaws.com/chef-releng/openssl/openssl-1.0.2zi.tar.gz

Thanks!

**Comment by kzalewski** [comment]
I'm sorry, but it already takes me a lot of effort to backport the patches from OpenSSL 3.0 into 1.1.1.  I don't have the bandwidth to do the same for the 1.0.2 release.  However, each of my commits makes it very clear which files were modified in order to apply the patch, so with some effort, you should be able to backport into 1.0.2.
